// Generated by Qodo Gen
const request = require('supertest');
const express = require('express');
const supabase = require('../config/supabase');
const authRouter = require('./auth');

// Mock supabase
jest.mock('../config/supabase', () => ({
  auth: {
    signUp: jest.fn(),
    signInWithPassword: jest.fn(),
    signOut: jest.fn(),
    getUser: jest.fn()
  }
}));

describe('Authentication Routes', () => {
  let app;

  beforeEach(() => {
    // Clear all mocks before each test
    jest.clearAllMocks();
    
    // Create a new Express app for each test
    app = express();
    app.use(express.json());
    app.use('/auth', authRouter);
  });

  describe('POST /auth/register', () => {
    it('should successfully register a new user with valid credentials', async () => {
      const mockUser = { id: '123', email: 'test@example.com' };
      const mockResponse = {
        data: { user: mockUser },
        error: null
      };

      supabase.auth.signUp.mockResolvedValue(mockResponse);

      const response = await request(app)
        .post('/auth/register')
        .send({
          email: 'test@example.com',
          password: 'password123'
        });

      expect(supabase.auth.signUp).toHaveBeenCalledWith({
        email: 'test@example.com',
        password: 'password123'
      });
      expect(response.status).toBe(200);
      expect(response.body).toEqual({
        message: 'Registration successful. Please check your email for verification.',
        user: mockUser
      });
    });

    it('should handle registration with invalid email format', async () => {
      const mockError = new Error('Invalid email format');
      const mockResponse = {
        data: null,
        error: mockError
      };

      supabase.auth.signUp.mockResolvedValue(mockResponse);

      const response = await request(app)
        .post('/auth/register')
        .send({
          email: 'invalid-email',
          password: 'password123'
        });

      expect(supabase.auth.signUp).toHaveBeenCalledWith({
        email: 'invalid-email',
        password: 'password123'
      });
      expect(response.status).toBe(400);
      expect(response.body).toEqual({
        error: mockError.message
      });
    });
  });

  describe('POST /auth/login', () => {
    it('should successfully login a user with valid credentials', async () => {
      const mockUser = { id: '123', email: 'test@example.com' };
      const mockSession = { access_token: 'mock-token' };
      const mockResponse = {
        data: { user: mockUser, session: mockSession },
        error: null
      };

      supabase.auth.signInWithPassword.mockResolvedValue(mockResponse);

      const response = await request(app)
        .post('/auth/login')
        .send({
          email: 'test@example.com',
          password: 'password123'
        });

      expect(supabase.auth.signInWithPassword).toHaveBeenCalledWith({
        email: 'test@example.com',
        password: 'password123'
      });
      expect(response.status).toBe(200);
      expect(response.body).toEqual({
        message: 'Login successful',
        session: mockSession,
        user: mockUser
      });
    });

    it('should handle login with invalid credentials', async () => {
      const mockError = new Error('Invalid login credentials');
      const mockResponse = {
        data: null,
        error: mockError
      };

      supabase.auth.signInWithPassword.mockResolvedValue(mockResponse);

      const response = await request(app)
        .post('/auth/login')
        .send({
          email: 'test@example.com',
          password: 'wrongpassword'
        });

      expect(supabase.auth.signInWithPassword).toHaveBeenCalledWith({
        email: 'test@example.com',
        password: 'wrongpassword'
      });
      expect(response.status).toBe(400);
      expect(response.body).toEqual({
        error: mockError.message
      });
    });
  });
});
